### ISSUE TITLE
Debugging fails: "cannot load twice"

### ISSUE THREAD

**Issue by tloehr** [asebak/embeddedlinux-jvmdebugger-intellij#35]
When I try to start the debugging process it fails with the following error message:

```bash
pi@raspberrypi ~ $ sudo java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=12345 -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:52231,suspend=y,server=n -cp classes:lib/'*' main.MissionBox;
ERROR: Cannot load this JVM TI agent twice, check your java command line for duplicate jdwp options.
Error occurred during initialization of VM agent library failed to init: jdwp
```

Previous versions didn't have this problem. When I change the command line by removing the "-Xrunjdwp" part, the debugger starts fine (at least in a shell). Didn't find a way to edit the generated command line in the IDE.

And thanks for that great plugin. Besides the bug, I am totally in love with it. :-)

**Comment by asebak** [comment]
@tloehr Hey thanks for the love of the plugin :+1: I will look into it.  But can you take a screenshot of your run configuration settings

**Comment by asebak** [comment]
just made a new release which should be avaiable in the store shortly v0.35

**Comment by tloehr** [comment]
Sorry wasnt fast enough for the screenshot. Thanks for your help.

---
sent from my iPhone
